// Auto-generated by scripts/extract-palette.mjs — do not edit manually.
// Re-run `node scripts/extract-palette.mjs` after adding or changing images.

export interface CaseStudyPalette {
  from:   string; // gradient start
  to:     string; // gradient end
  accent: string; // accent color (≥ 4.5:1 on --p-bg)
}

export const palettes: Record<string, CaseStudyPalette> = {
  ades: { from: "#19a57e", to: "#0a4434", accent: "#128166" },
};
